[features]
seeds = false
skip-lint = false
[programs.localnet]
wba_vault0 = "Dq4UUdY4UBb6BiLRnRXBoF6xW7VZ9FKWNHZY94Zs4YmW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/resiquents/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
